import { describe, it, expect, vi } from "vitest";
import { render, screen, userEvent } from "@/test/test-utils";
import { VideoPreview } from "../video-preview";

describe("VideoPreview", () => {
  it("renders video player with controls", () => {
    render(<VideoPreview videoUrl="https://r2.dev/video.mp4" provider="Luma" onClose={vi.fn()} />);
    const video = screen.getByTestId("video-player") as HTMLVideoElement;
    expect(video).toBeInTheDocument();
    expect(video.controls).toBe(true);
  });

  it("shows provider name", () => {
    render(<VideoPreview videoUrl="https://r2.dev/video.mp4" provider="Runway" onClose={vi.fn()} />);
    expect(screen.getByText("Generated by Runway")).toBeInTheDocument();
  });

  it("has download link", () => {
    render(<VideoPreview videoUrl="https://r2.dev/video.mp4" provider="Luma" onClose={vi.fn()} />);
    const link = screen.getByText("Download Video").closest("a");
    expect(link?.href).toContain("video.mp4");
  });

  it("calls onClose when close button is clicked", async () => {
    const user = userEvent.setup();
    const onClose = vi.fn();
    render(<VideoPreview videoUrl="https://r2.dev/video.mp4" provider="Luma" onClose={onClose} />);
    // CloseButton rendered by Chakra
    const closeBtn = screen.getByRole("button", { name: /close/i });
    await user.click(closeBtn);
    expect(onClose).toHaveBeenCalled();
  });
});
