"use client";

interface VideoPreviewProps {
  videoUrl: string;
  provider: string;
  onClose: () => void;
}

export function VideoPreview({ videoUrl, provider, onClose }: VideoPreviewProps) {
  return (
    <div style={{
      borderRadius: "16px",
      backgroundColor: "var(--color-surface-raised)",
      border: "1px solid var(--color-border-light)",
      overflow: "hidden",
      boxShadow: "0 8px 30px rgba(0,0,0,0.08)",
    }}>
      <div style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "16px 20px",
        borderBottom: "1px solid var(--color-border-light)",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <div className="brand-gradient" style={{
            width: "32px",
            height: "32px",
            borderRadius: "8px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}>
            <svg width="16" height="16" fill="white" viewBox="0 0 24 24"><path d="M8 5v14l11-7z" /></svg>
          </div>
          <div>
            <div style={{ fontWeight: 600, fontSize: "15px", color: "var(--color-text-primary)" }}>Preview</div>
            <div style={{ fontSize: "12px", color: "var(--color-text-secondary)" }}>Generated by {provider}</div>
          </div>
        </div>
        <button
          onClick={onClose}
          style={{
            border: "none",
            background: "none",
            cursor: "pointer",
            padding: "6px",
            color: "var(--color-text-muted)",
            borderRadius: "6px",
          }}
        >
          <svg width="20" height="20" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <video
        src={videoUrl}
        style={{ width: "100%", aspectRatio: "16/9", display: "block", backgroundColor: "#000" }}
        controls
        autoPlay
        loop
        data-testid="video-player"
      />

      <div style={{ padding: "16px 20px", borderTop: "1px solid var(--color-border-light)", backgroundColor: "var(--color-surface)" }}>
        <a href={videoUrl} download target="_blank" rel="noopener noreferrer" style={{ textDecoration: "none", display: "block" }}>
          <button className="brand-btn" style={{
            width: "100%",
            height: "44px",
            borderRadius: "10px",
            border: "none",
            fontSize: "14px",
            fontWeight: 600,
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "8px",
          }}>
            <svg width="16" height="16" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            Download Video
          </button>
        </a>
      </div>
    </div>
  );
}
