"use client";

import { Button } from "@/components/ui/button";

interface VideoPreviewProps {
  videoUrl: string;
  provider: string;
  onClose: () => void;
}

export function VideoPreview({
  videoUrl,
  provider,
  onClose,
}: VideoPreviewProps) {
  return (
    <div className="rounded-2xl bg-white border border-zinc-200 overflow-hidden shadow-xl">
      <div className="flex items-center justify-between px-5 py-4 border-b border-zinc-100">
        <div className="flex items-center gap-3">
          <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-violet-600 to-indigo-600 flex items-center justify-center">
            <svg className="h-4 w-4 text-white" fill="currentColor" viewBox="0 0 24 24">
              <path d="M8 5v14l11-7z" />
            </svg>
          </div>
          <div>
            <h3 className="font-semibold text-zinc-900">Preview</h3>
            <p className="text-xs text-zinc-500">Generated by {provider}</p>
          </div>
        </div>
        <Button variant="ghost" size="sm" onClick={onClose} className="text-zinc-400 hover:text-zinc-900">
          <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </Button>
      </div>

      <video
        src={videoUrl}
        className="w-full aspect-video bg-black"
        controls
        autoPlay
        loop
        data-testid="video-player"
      />

      <div className="px-5 py-4 bg-zinc-50 border-t border-zinc-100">
        <a href={videoUrl} download target="_blank" rel="noopener noreferrer" className="block">
          <Button className="w-full h-11 rounded-xl bg-zinc-900 hover:bg-zinc-800">
            <svg className="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            Download Video
          </Button>
        </a>
      </div>
    </div>
  );
}
