"use client";

import { Box, HStack, VStack, Heading, Text, Button, CloseButton } from "@chakra-ui/react";

interface VideoPreviewProps {
  videoUrl: string;
  provider: string;
  onClose: () => void;
}

export function VideoPreview({ videoUrl, provider, onClose }: VideoPreviewProps) {
  return (
    <Box bg="white" borderRadius="2xl" border="1px solid" borderColor="gray.200" overflow="hidden" shadow="xl">
      <HStack justify="space-between" px="5" py="4" borderBottom="1px solid" borderColor="gray.100">
        <VStack align="start" gap="0">
          <Heading size="sm">Preview</Heading>
          <Text fontSize="xs" color="gray.500">Generated by {provider}</Text>
        </VStack>
        <CloseButton onClick={onClose} />
      </HStack>

      <video
        src={videoUrl}
        style={{ width: "100%", aspectRatio: "16/9", display: "block", backgroundColor: "black" }}
        controls
        autoPlay
        loop
        data-testid="video-player"
      />

      <Box px="5" py="4" borderTop="1px solid" borderColor="gray.100" bg="gray.50">
        <a href={videoUrl} download target="_blank" rel="noopener noreferrer">
          <Button w="full" colorPalette="purple" size="lg">
            Download Video
          </Button>
        </a>
      </Box>
    </Box>
  );
}
